### PR TITLE
Detect XSS inside or after HTML comments

### PR DESCRIPTION
**Pull request by quadule**
While testing against a known vulnerable app, I noticed that a reflected XSS currently isn't detected if it appears either inside of or following a HTML comment.

### CODE REVIEW

**Comment by postmodern** [comment]
@quadule clever! I hadn't thought about XSS *within* a HTML comment.

**Review by postmodern — CHANGES_REQUESTED** [review]
Just need additional documentation for `Context#location` that mentions the new `:comment` value.

**Comment by postmodern** [comment]
I will also have to manually merge into the `0.2.0` branch, since this is a new feature.

**Comment by quadule** [comment]
Ok, I updated the docs for that and the nilable `tag` too, thanks!

**Review by postmodern — APPROVED** [review]

**Comment by postmodern** [comment]
Changed my mind on merging into `0.2.0` and merged into `main`. Will try to get this released in the next patch-version ASAP. Thanks!

**Pull request merged**
